### ISSUE TITLE
Add hashes to js tracker

### ISSUE THREAD

**Issue by hwolff00** [Parsely/functional-js-slides#1]

**Comment by hwolff00** [comment]
completed by @wbrgss !!!

**Comment by wbrgss** [comment]
@hwolff00 is this issue in the wrong repo? 😁

**Comment by hwolff00** [comment]
hahahahahahaha @wbrgss oops

**Comment by wbrgss** [comment]
Now I want to listen to Andrew's talk, looks like a great topic
